{% set version = "0.2.3" %}

package:
  name: pdftopng
  version: {{ version }}

source:
  - url: https://github.com/vinayak-mehta/pdftopng/archive/v{{ version }}.tar.gz
    sha256: 2b0cda9b7e151d67a182bb753138309c3a6b035939577c5527a34a2c1ef96b64
    patches:
      - 0001-fix-setup.patch
      - setOverprintPreview.patch
  - url: https://gitlab.freedesktop.org/poppler/poppler/-/raw/ee2af17e916e6310ab25b92a638df380b18a24ee/utils/numberofcharacters.h
    sha256: 285258e387080c775e4f6f5bca652e9e707c3beac83c6625d3b840c4e13c6440

build:
  number: 14
  entry_points:
    - pdftopng = pdftopng.cli:cli

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - cython
    - pybind11
    - poppler
    - pip
  run:
    - python
    - poppler
    - click

test:
  imports:
    - pdftopng

about:
  home: https://github.com/vinayak-mehta/pdftopng
  license: GPL-2.0-only
  license_file: LICENSE
  summary: A PDF to PNG conversion library (based on pdftoppm from poppler) 

extra:
  recipe-maintainers:
    - izahn
    - vinayak-mehta
